

export const REQUEST_ADD_POST = 'REQUEST_ADD_POST';
export const RECEIVE_ADD_POST = 'RECEIVE_ADD_POST';

export const REQUEST_EDIT_POST = 'REQUEST_EDIT_POST';
export const RECEIVE_EDIT_POST = 'RECEIVE_EDIT_POST';

export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST';


export const REQUEST_GET_POST = 'REQUEST_GET_POST';
export const RECEIVE_GET_POST = 'RECEIVE_GET_POST';


export const ERROR = 'ERROR';